name: Code Quality and Security Checks

on:
  pull_request:
    paths:
      - '**.py'
      - '**.ipynb'

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbqa flake8 pylint bandit nbformat
      
      # Step 1: Check Naming Conventions and Linting
      - name: Check Naming Conventions and Linting
        run: |
          # Check .ipynb files for naming conventions and linting issues using nbqa
          nbqa flake8 .
          nbqa pylint . --rcfile=config/pylintrc

          # Check .py files for naming conventions and linting issues directly
          flake8 .
          pylint . --rcfile=config/pylintrc

      # Step 4: Security Vulnerability Check
      - name: Security Vulnerability Check
        run: |
          # Use bandit to check for security vulnerabilities in .ipynb and .py files
          nbqa bandit -r .
          bandit -r .

