name: Notebook Quality Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  notebook-checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbqa flake8 pylint bandit nbformat

    - name: Lint Notebooks
      run: |
        # Lint the Python code in .ipynb files using flake8
        nbqa flake8 .

    - name: Check for Large Output Cells
      run: |
        # Check for large output cells in notebooks
        for notebook in $(find . -name "*.ipynb"); do
          if jupyter nbconvert --to notebook --stdout "$notebook" | grep -q '"output_type": "display_data"'; then
            echo "Notebook $notebook has large output cells. Please clean it up."
            exit 1
          fi
        done

    - name: Check for Function Docstrings
      run: |
        # Use pylint to check for missing function docstrings
        nbqa pylint --disable=all --enable=missing-function-docstring .

    - name: Security Vulnerability Check
      run: |
        # Use bandit to check for security vulnerabilities in notebook code
        nbqa bandit -r .
