name: Pull Request Checks
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Pull Request Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@v45.0.1
        with:
          separator: ","

      - name: Get Markdown files
        id: changed_md_files
        uses: tj-actions/changed-files@v45.0.1
        with:
          files: |
            *.md
        
      - name: Print the Changed Files
        run: |
          echo Changed files: ${{ steps.changed_files.outputs.all_changed_files }}
          echo Markdown files: ${{ steps.changed_md_files.outputs.all_changed_files }}

      # - name: Check for file naming conventions
      #   run: |
      #     all_files=$(echo "${{ steps.changed_files.outputs.all_changed_files }}" | tr "," "\n")

      #     for $file in all_files; do
      #       if $

          
      #       echo "This PR contains PDF or word (.docx) files, please remove them and try again."
      #       exit 1
      #     else
      #       echo "This PR does not contain PDF or word (.docx) files."
      #     fi

      - name: Check for PDF and Word files
        run: |
          echo "${{ steps.changed_files.outputs.all_changed_files }}" | tr "," "\n" | if grep -q -e ".docx" -e ".pdf"; then
            echo "This PR contains PDF or word (.docx) files, please remove them and try again."
            exit 1
          else
            echo "This PR does not contain PDF or word (.docx) files."
          fi

      - name: Setup Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install check dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbqa flake8 pylint bandit nbformat
      
      - name: Execute linting and security check on Python files
        run: |
          py_files=$(echo "${{ steps.changed_files.outputs.all_changed_files }}" | tr "," "\n" | grep ".py$" || true)
          if [ -n "$py_files" ]; then
            for file in $py_files; do
              flake8 $file
              pylint $file --rcfile=ci_build/pylintrc
              # bandit -r $file
            done
          else
            echo "No Python files to lint and check."
          fi

      - name: Execute linting and security check on Jupyter Notebooks
        run: |
          nb_files=$(echo "${{ steps.changed_files.outputs.all_changed_files }}" | tr "," "\n" | grep ".ipynb$" || true)
          if [ -n "$nb_files" ]; then
            for file in $nb_files; do
              nbqa flake8 $file
              nbqa pylint $file --rcfile=ci_build/pylintrc
              # nbqa bandit -r $file
            done
          else
            echo "No Jupyter Notebooks to lint."
          fi
