name: Linting Workflow

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install pylint flake8

      - name: Run Flake8 and continue on error
        run: |
          flake8 . > flake8_output.txt || true

      - name: Run Pylint and continue on error
        run: |
          find . -name "*.py" | xargs pylint > pylint_output.txt || true

      - name: Print Flake8 results
        run: cat flake8_output.txt

      - name: Print Pylint results
        run: cat pylint_output.txt

      - name: Check Flake8 result file for failures
        run: |
          if grep -q "E" flake8_output.txt; then
            echo "Flake8 found errors!" && exit 1
          fi

      - name: Check Pylint result file for failures
        run: |
          if grep -q "error" pylint_output.txt; then
            echo "Pylint found errors!" && exit 1
          fi
